### ISSUE TITLE
Error upon posting comments

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#1443] opened 2023-11-04 14:10 UTC
### Steps to reproduce the problem

1. Post a comment on an answer
2. `TypeError` is thrown.

### Expected behaviour

The subscribe action on the answer should be updated.

### Actual behaviour

`TypeError` is thrown and an error toast is displayed to the user.

### Specifications

Retrospring 20231028.1

Firefox 118.0.2

**Comment by chahmedejaz** [comment] 2023-11-09 08:38
Hey @raccube - I spiked on this issue and here are my findings:
- This is caused by these changes:
  - https://github.com/Retrospring/retrospring/pull/1417/files#diff-dae21ea85421965fd9b72a386fe3461aaca6bc45c3b67d9dd7930c5b01a584dcL3-L10
  - https://github.com/Retrospring/retrospring/pull/1417/files#diff-c52ed63dab8f18456411306029b0efb69cdba2ea74d61c060ef619c02731330cR1-R3
- And in the following lines we are not getting the `sub`, hence the error:
- https://github.com/Retrospring/retrospring/blob/43140105355219ebf23802d9ac506fdb60a562c9/app/javascript/retrospring/features/answerbox/comment/new.ts#L35-L37
- Please suggest the path forward. 
- After looking at the above changes, I believe these lines should be removed from here. 

PS: I'd love to fix this, can you please assign it to me? Thanks :)

**Comment by raccube** [comment] 2023-11-09 15:52
@chahmedejaz If you want to solve an issue, you can always just open a pull request without being assigned to it.

**Comment by chahmedejaz** [comment] 2023-11-09 15:55
> @chahmedejaz If you want to solve an issue, you can always just open a pull request without being assigned to it. 

Sure, thank you :)

**Closed as completed** 2023-11-12 00:19 UTC
Labels: bug
