### ISSUE TITLE
We need a search feature!

### ISSUE THREAD

**Issue by inhahe** [Retrospring/retrospring#1720] opened 2024-04-29 07:49 UTC
### Pitch

We need a way to search the site for specific posts. I don't know if there's no search feature because nobody felt like implementing one, or because searches would take too many system resources, but if it's the latter, there exist searching and indexing libraries that make searching a lot of text really quick/efficient. For example, there's Whoosh for Python, but I know Retrospring isn't written in Python, just saying. Maybe there's a Ruby one or one you can wrap in Ruby. It would only require a lot of system resources once, to initially populate the database, then every time a new post is made, just add the page to the database.

### Motivation

I've been trying to find a specific post I made for like 2 hours at least. I'm at 3 years ago now. I have to repeatedly click the "Load more" button, and the more times I do it the slower it gets. And it takes so long to load that sometimes I accidentally click "Load more" again before it's finished loading, and by the time it registers my click there's another link in that spot so it navigates to that other page and then I have to go back to the previous page and it takes the browser so long to load the previous page that the hung page dialog comes up a number of times by the time it finishes. And I'd just use the download your history feature, but the last I knew that function didn't work anymore for some reason. 

The reason I'm searching is that I find the idea of backward causality logically contradictory, but it's hard for me to articulate/flesh out why, and I did it well once in a post that I believe was on Retrospring. And I want to show it to someone in an IRC philosophy channel I was talking with who mentioned backward causality. (Maybe my understanding is wrong, but then maybe he could show me how it's wrong.) And I don't like losing my ideas and having to try to recreate them.

Meanwhile I'm trying to search for a different thing that's more recent in another tab, and the "Load more" button isn't working in that tab, which I guess has something to do with the really long search I'm doing in the first tab.

**Comment by pixeldesu** [comment] 2024-04-29 14:23
Please use the search feature before opening another feature request, this is a duplicate of #13.

Also, we do want search ourselves and [already experimented with it](https://github.com/Retrospring/retrospring/pull/1406), it just needs to be finished/built by someone. Retrospring is a hobby project and somewhat motivation-driven as well, so _it'll be there when someone adds it_.

**Closed as not planned by pixeldesu** 2024-04-29 14:23 UTC
Labels: suggestion
