### ISSUE TITLE
Add a "Share to fedi" option

### ISSUE THREAD

**Issue by normikoto** [Retrospring/retrospring#1083] opened 2023-02-13 23:36 UTC
### Pitch

There should be an option to share answers on a Fediverse instance in the Share menu.

Not sure how feasible this would be considering the wide range of software that Fediverse instances run on but if it works on at least the top three implementations (Mastodon, Pleroma/Akkoma, *key), then it should be good enough.

### Motivation

Since Retrospring is quite popular amongst Fediverse users, it makes sense to make it easier to share answers to questions on Fediverse instances as well.

**Comment by a1batross** [comment] 2023-02-14 02:44
Mastodon has /share?text= route for that. I'm not sure if there is any equivalent for Pleroma. And there is definitely no fedi-specific standard for sharing on fedi mobile clients, only generic sharing mechanism.

**Comment by nilsding** [comment] 2023-02-14 04:00
hi, this has already been implemented in #1046 and will be part of the next release.

we confirmed that it works well with Mastodon and Misskey -- no idea about pleroma though.

**Closed as completed by nilsding** 2023-02-14 04:00 UTC
Labels: suggestion

**Comment by nanopone** [comment] 2023-11-01 23:49
i would like this to be re-opened as there's literally no way to do this on akkoma (pleroma) as far as i can see, even when using the mastodon front end. using retrospring and posting my answers to my akkoma instance is extremely frustrating because i have to copy the question, the answer, and the link, and manually format a post. as someone who gets 10s of question a week, this is monotonous and makes me not want to open retrospring at all

**Comment by pixeldesu** [comment] 2023-11-02 21:38
@nanopone implementing per-user Mastodon/Pleroma/whatever OAuth and API support would be a massive undertaking I'm not sure we will muster up in the recent time.

No ETA for it, but once #395 drops in it's initial form, people can just follow your Retrospring account on fedi if they want to receive your answers on their feed.

Working towards the goal of integrating AP is probably more worthwhile than trying to cram in external APIs.

**Comment by nanopone** [comment] 2023-11-04 15:18
> @nanopone implementing per-user Mastodon/Pleroma/whatever OAuth and API support would be a massive undertaking I'm not sure we will muster up in the recent time.
> 
> No ETA for it, but once #395 drops in it's initial form, people can just follow your Retrospring account on fedi if they want to receive your answers on their feed.
> 
> Working towards the goal of integrating AP is probably more worthwhile than trying to cram in external APIs.

here's an alternative proposal then: when you answer a question, along with twitter and all the other websites you can share to, why not add a "copy" button which copies a fully formatted post with the question, answer, and link, that you can just paste wherever you like?

**Comment by pixeldesu** [comment] 2023-11-05 09:32
@nanopone that works! I'll create a separate issue for that request then!
